facts = [
    'Owls have an excellent sense of hearing.',
    'Owls can’t move their eyes.',
    'Owls can turn their heads almost completely around, as much as 270 degrees.',
    'The baby birds of Owl are called Chicks.',
    'Owls are active at night.',
    'A group of owls is called a parliament.',
    'Most owls hunt small mammals and other birds.',
    'Some owl species hunt fish.',
    'There are around 200 different owl species.',
    'Owls are farsighted.',
    'Owls are very quiet when flighting compared to other birds of prey.',
    'Barn owls have a heart shaped face.',
    'An owl can be found on every continent except Antarctica.',
    'The size of the owl depends on the species.',
    'The Elf Owl is one of the smallest owls in the world.',
    'Eurasian Eagle-Owl and Blakiston’s Fish Owl are one of the biggest owls in the world.',
    'All owls can be divided into two large groups: barn and true owls.',
    'There are only 19 species belong to a Barn owl.',
    'There are around 190 species of True owls.',
    'Owls do not chew their food because they do not have teeths.',
    'Barn owls are very beneficial for farmers because they can eat up to 1000 mice each year.',
    'Barn Owls eat mostly mice, voles, shrews, and rats.',
    'Barn Owls have very long legs, toes, and talons which allows them to catch prey hidden under long grass.',
    'Their eyes are very sensitive.',
    'Barn Owls usually hunt at night.',
    'Tyto alba is the scientific Latin name for Barn Owl.',
    'Their feathers can be brown, rust, gray, white, and black.',
    'Barn Owls have lop-sided ears.',
    'Barn Owl feathers are super soft.',
    'Owl can fly silently.',
    'Owls lay between a few to a dozen eggs.',
    'Owls are solitary creatures.',
    'Some species of owls have ear-like structures on their head.',
    'Owl’s eggs do not hatch at the same time.',
    'The great Horned Owls are the top predator of the Barred Owls.',
    'The Lifespan of owls is around 20 years.',
    'In appearance, the largest North American owl is the Great Gray Owl which is up to 32 inches tall.',
    'Northern Saw-whet Owls can travel long distances.',
    'The long-legged burrowing owl lives in North and South America.',
    'According to Greek mythology, if Greek soldiers saw an owl fly during battle, they took it as a sign of coming victory.',
    'Many owl species have asymmetrical ears. When located at different heights on the owl’s head, their ears are able to pinpoint the location of sounds in multiple dimensions. Ready, aim, strike.',
    'The eyes of an owl are not true “eyeballs.” Their tube-shaped eyes are completely immobile, providing binocular vision which fully focuses on their prey and boosts depth perception.',
    'Owls can rotate their necks 270 degrees. A blood-pooling system collects blood to power their brains and eyes when neck movement cuts off circulation.',
    'A group of owls is called a parliament. This originates from C.S. Lewis’ description of a meeting of owls in The Chronicles of Narnia.',
    'Owls hunt other owls. Great Horned Owls are the top predator of the smaller Barred Owl.',
    'The tiniest owl in the world is the Elf Owl, which is 5 - 6 inches tall and weighs about 1 ½ ounces. The largest North American owl, in appearance, is the Great Gray Owl, which is up to 32 inches tall.',
    'The Northern Hawk Owl can detect—primarily by sight—a vole to eat up to a half a mile away.',
    'In fat years when mice are plentiful, usually monogamous Boreal Owls are apt to be promiscuous. Because easy prey means less work for parents feeding their young, males have been caught mating with up to three females, while females have been seen with at least one beau on the side.',
    'Barn Owls swallow their prey whole—skin, bones, and all—and they eat up to 1,000 mice each year.',
    'Northern Saw-whet Owls can travel long distances over large bodies of water. One showed up 70 miles from shore near Montauk, New York.',
    'Not all owls hoot! Barn Owls make hissing sounds, the Eastern Screech-Owl whinnies like a horse, and Saw-whet Owls sound like, well, an old whetstone sharpening a saw. Hence the name.',
    'Owls are zygodactyl, which means their feet have two forward-facing toes and two backward-facing toes. Unlike most other zygodactyl birds, however, owls can pivot one of their back toes forward to help them grip and walk.'
]